### ISSUE TITLE
Carpeta Target

### ISSUE THREAD

**Issue by mgejer** [mackhood/tp-arena-sierra-jugo-final#1]
Chicos, fijense de agregar la carpeta Target al git ignore, no se debe pushear al repo

**Comment by mgejer** [comment]
Chicos, agreguenlo como 
target/*
De esta forma elimina todo aquello que este dentro de esta carpeta.

Ademas, fijense que ya está esta carpeta subida, eliminenla por favor.

**Comment by mackhood** [comment]
Ahí elimine la carpeta y modifique el gitignore
