### ISSUE TITLE
Archivos sin Uso

### ISSUE THREAD

**Issue by mgejer** [mackhood/tp-arena-sierra-jugo-final#2]
Chicos, encontre estos archivos que no estan siendo usados, traten de eliminarlos y ver que no haya otro:

DatosUsuario.java
NotasAplicacion.java

**Comment by mackhood** [comment]
Hola martin el archivo DatosUsuario.java pertenece al master , el tp terminado se encuentre en tpv2 , no lo estaria encontrando ese archivo en esta ultima rama, el archivo NotasAplicacion.java ya lo borre ahora lo subo
