### ISSUE TITLE
Jerarquia de Asignaciones

### ISSUE THREAD

**Issue by mgejer** [mackhood/tp-arena-sierra-jugo-final#3]
Arreglen la jerarquia de clases para no tener una clase abstracta unicamente por atrbutos. en todo caso deberia ser una interfaz.
Tampoco utilice un ArrayList como tipo de atributo, intenten usar las interfaces (List) para declarar atributos

**Comment by mackhood** [comment]
Hola martin , estuve viendo y la clase abstracta no estaria unicamente por atributos ya que el metodo actualizarEstado me permitiria no repetir logica ya que ambas clases asignaciones deben entenderlo para cambiar de estado, si borrara la clase abstracta tendria que definir en cada clase el tipo de criterio y la implementacion del metodo seria muy similar, en cambio con la clase abstracta podemos usar la interfaz Criterio ahorrandonos codigo.
Los arrrayList ya los modifique.
Saludos

**Comment by mgejer** [comment]
Por el modelo que estan planteando, la clase asignacion está asi:

 ````Java

```
